trigger:
- main
- stage

variables:
- name: TriggeredBranch
  value: $[ 'refs/heads/$(Build.SourceBranchName)' ]
- name: DockerImageName
  value: mydockerimage
- name: DockerRegistry
  value: mydockerregistry.azurecr.io
- name: TagName
  value: latest

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: DockerBuildPush
    displayName: Docker Build and Push
    steps:
    - script: echo "Triggered Branch"
      displayName: Display Triggered Branch

    - bash: |
        if [ "$(TriggeredBranch)" == "refs/heads/main" ] || [ "$(TriggeredBranch)" == "refs/heads/stage" ]; then
          echo "Building Docker image..."
          docker build -t $(DockerRegistry)/$(DockerImageName):$(TagName) .
          docker push $(DockerRegistry)/$(DockerImageName):$(TagName)
        else
          echo "Skipping Docker build and push as not on main or stage branch"
        fi
      displayName: Docker Build and Push
