trigger:
  - main
  - stage

variables:
  tag: '$(Build.BuildId)'
  # imagePullSecret: acr-secret
  # imageRepository: prep-nursing
  # containerRegistry: prepxacr.azurecr.io
  branch: $(Build.SourceBranch)

stages:
- stage: Build
  displayName: Build Agent Images
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: CmdLine@2
      displayName: 'Build and Push Image'
      inputs:
        script: |
          echo $(Agent.BuildDirectory)
          echo '-------'
          whoami
          curl ifconfig.me
          # imageTag=$(if eq '$(Build.SourceBranch)' 'refs/heads/main' 'prod' '$(Build.SourceBranchName)')
          echo "Image Tag: $branch"
