trigger:
- main
- stage

variables:
- name: TriggeredBranch
  value: $[ 'refs/heads/$(Build.SourceBranchName)' ]

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: CheckBranch
    displayName: Check Branch Job
    steps:
    - script: |
        if [ "$(TriggeredBranch)" == "refs/heads/main" ]; then
          echo "I am from main branch"
        elif [ "$(TriggeredBranch)" == "refs/heads/stage" ]; then
          echo "I am from stage branch"
        else
          echo "I am from nowhere"
        fi
      displayName: Check Branch Name
