trigger:
  - main
  - stage

variables:
  tag: '$(Build.BuildId)'
  branchName: $( echo "$(Build.SourceBranch)" | sed 's/refs\/heads\///' )

stages:
- stage: Build
  displayName: Build Agent Images
  jobs:
  - job: Build
    displayName: Build
    steps:
    - ${{ if eq(variables['branchName'], 'main') }}:
      - script: |
          echo $(Agent.BuildDirectory)
          echo '-------'
          whoami
          curl ifconfig.me
          echo "My branch name is main"
        displayName: 'Build and Push Image for Main'
    - ${{ if eq(variables['branchName'], 'stage') }}:
      - script: |
          echo $(Agent.BuildDirectory)
          echo '-------'
          whoami
          curl ifconfig.me
          echo "My branch name is stage"
        displayName: 'Build and Push Image for Stage'
    - ${{ if ne(variables['branchName'], 'main') && ne(variables['branchName'], 'stage') }}:
      - script: |
          echo $(Agent.BuildDirectory)
          echo '-------'
          whoami
          curl ifconfig.me
          echo "Branch Name: ${{ variables.branchName }}"
        displayName: 'Build and Push Image for Other Branches'
